name: Deploy Worker
on:
  push:
    branches: [ main ]
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
        with: { version: 9 }
      - run: pnpm install --frozen-lockfile || npm ci
      - name: Publish via Wrangler
        working-directory: goldshore-api
        run: npx wrangler deploy --config wrangler.jsonc
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CF_API_TOKEN }}
          CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CF_ACCOUNT_ID }}
          CORS_ALLOWED_ORIGINS: "https://goldshore.org,https://api.goldshore.org"
