name: Deploy Gold Shore Web

on:
  push:
    branches:
      - main
    paths-ignore:
      - '.github/workflows/worker-deploy.yml'
      - 'src/index.ts'
      - 'wrangler.toml'
      - 'README.md'
      - 'docs/**'
  workflow_dispatch:

jobs:
  build-and-deploy:
    name: Build and deploy Pages project
    runs-on: ubuntu-latest

    permissions:
      contents: read

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm

      - name: Install dependencies
        run: npm ci

      - name: Build
        run: npm run build

      - name: Deploy to Cloudflare Pages
        uses: cloudflare/pages-action@v1
        with:
          apiToken: ${{ secrets.CF_API_TOKEN }}
          accountId: ${{ secrets.CF_ACCOUNT_ID }}
          projectName: goldshore-web
          directory: dist
          gitHubToken: ${{ secrets.GITHUB_TOKEN }}
